= Application Spice Operator

This Ansible based operator helps in spicing the Kubernetes applications for some extra capabilities. The `capabilites` - are the extra components that are added to your cluster, to make to cook a new `Recipe` - e.g a serverless recipe with Knative or pipelines with Tektoncd or add an Ingress using contour

== Role Dependencies

This opeator uses the role https://github.com/kameshsampath/ansible-role-kubernetes-app-spices[kameshsampath.k8s_app_spices]

== Installing the Operator

[source,bash,attributes]
----
kubectl create ns demos
kubectl apply -n demos -f https://raw.githubusercontent.com/kameshsampath/app-spice-operator/master/deploy/service_account.yaml
kubectl apply -n demos -f https://raw.githubusercontent.com/kameshsampath/app-spice-operator/master/deploy/role_binding.yaml #<1>
kubetl apply -n demos -f https://raw.githubusercontent.com/kameshsampath/app-spice-operator/master/deploy/operator.yaml
----

<1> Make sure to update the subjects namespace to `demos`

Wait for the *app-spice-operator* to be up and running:

[source,bash]
----
watch kubectl get pods -n demos
----

== Example CRs(recipes)

Based on the recipes you need you can deploy one from crds folder:

=== Knative 

[source,bash]
----
kubectl apply -n demos -f https://raw.githubusercontent.com/kameshsampath/app-spice-operator/master/deploy/crds/knative_recipe_cr.yaml
----

The command above should deploy Knative Serving and Eventing components in `knative-serving` and `knative-eventing` namespaces.

=== Tetkoncd 

[source,bash]
----
kubectl apply -n demos -f https://raw.githubusercontent.com/kameshsampath/app-spice-operator/master/deploy/crds/tektoncd_recipe_cr.yaml
----

The command above should deploy Tektoncd Pipelines and Triggers components in `tektoncd-pipelines` namespace.

=== Knative with Tektoncd

[source,bash]
----
kubectl apply -n demos -f https://raw.githubusercontent.com/kameshsampath/app-spice-operator/master/deploy/crds/knative_pipelines_recipe.yaml
----
