---
roles:
  - name: kameshsampath.k8s_app_spices
  - name: kameshsampath.kind
  - name: kameshsampath.openshift_app_spices

collections:
  - name: community.kubernetes
    version: '<1.0.0'
  - operator_sdk.util
