---
- name: Knative Verify
  hosts: localhost
  connection: local
  gather_facts: no

  collections:
    - community.kubernetes

  vars:
    kn_test_namespace: osdk-knative-test

  tasks:
    - name: "Create {{ kn_test_namespace }} namespace"
      k8s:
        api_version: v1
        kind: Namespace
        name: '{{ kn_test_namespace }}'
  
    - name: Create the CustomeResource and wait for reconciliation to complete
      k8s:
        state: present
        namespace: '{{ namespace }}'
        definition: '{{ custom_resource }}'
        wait: yes
        wait_timeout: 300
        wait_condition:
          type: Running
          reason: Successful
          status: "True"

    - name: Get Pods
      k8s_info:
        api_version: v1
        kind: Pod
        namespace: '{{ namespace }}'
      register: pods

    - name: Example assertion
      assert:
        that: (pods | length) > 0
    
- import_playbook: serving_verify.yml
- import_playbook: eventing_verify.yml