apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: recipes.spice.kameshs.dev
spec:
  group: spice.kameshs.dev
  names:
    kind: Recipe
    listKind: RecipeList
    plural: recipes
    singular: recipe
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
    subresources:
      status: {}
