apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: workshoprecipes.spice.kameshs.dev
spec:
  group: spice.kameshs.dev
  names:
    kind: WorkshopRecipe
    listKind: WorkshopRecipeList
    plural: workshoprecipes
    singular: workshoprecipe
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
    subresources:
      status: {}
