---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    requirements-file: requirements.yml
driver:
  name: delegated
lint: |
  set -e
  yamllint .
platforms:
- name: openshift-cluster
  groups:
  - k8s
provisioner:
  name: ansible
  lint: |
    set -e
    ansible-lint
  inventory:
    group_vars:
      all:
        namespace: ${TEST_OPERATOR_NAMESPACE:-osdk-test}
    host_vars:
      localhost:
        ansible_python_interpreter: '{{ ansible_playbook_python }}'
        deploy_dir: ${MOLECULE_PROJECT_DIRECTORY}/deploy
        template_dir: ${MOLECULE_PROJECT_DIRECTORY}/molecule/templates
        operator_image: ${OPERATOR_IMAGE:-"quay.io/kameshsampath/app-spice-operator"}
        operator_pull_policy: ${OPERATOR_PULL_POLICY:-"Always"}
        molecule_no_log: False
        serverless_test: True
        tektoncd_test: False
  env:
    K8S_AUTH_KUBECONFIG: ${KUBECONFIG:-"~/openshift/gcp/auth/kubeconfig"}
verifier:
  name: ansible
  lint: |
    set -e
    ansible-lint
