---
- name: Prepare
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: "{{ molecule_no_log }}"
  collections:
   - community.kubernetes

  vars:
    deploy_dir: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/deploy"

  tasks:
    - name: Create Custom Resource Definition
      k8s:
        definition: "{{ lookup('file', '/'.join([deploy_dir, 'crds/spice.kameshs.dev_recipes_crd.yaml'])) }}"
      with_items:
        - spice.kameshs.dev_recipes_crd.yaml
        - spice.kameshs.dev_openshiftrecipes_crd.yaml
        - spice.kameshs.dev_workshoprecipes_crd.yaml

    - name: Create namespace
      k8s:
        api_version: v1
        kind: Namespace
        name: '{{ namespace }}'

    - name: Create RBAC resources
      k8s:
        definition: "{{ lookup('template', '/'.join([template_dir, item])) }}"
        namespace: '{{ namespace }}'
      with_items:
        - role_binding.yaml.j2
        - service_account.yaml.j2
