---
- name: Verify
  hosts: localhost
  connection: local
  gather_facts: no
  no_log: "{{ molecule_no_log }}"

  collections:
    - community.kubernetes

- import_playbook: ../knative/verify.yml
  vars:
    custom_resource: "{{ lookup('template', '/'.join([deploy_dir, 'crds','openshiftrecipes','openshift_serverless_cr.yaml'])) | from_yaml }}"
  when: serverless_test | default(False)

- import_playbook: ../tektoncd/verify.yml
  vars:
    custom_resource: "{{ lookup('template', '/'.join([deploy_dir, 'crds','openshiftrecipes','openshit_pipelines_cr.yaml'])) | from_yaml }}"
    ingress_namespace: contour-system
  when: tektoncd_test | default(False)
